services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    environment:
      TZ: $TZ
      WEBUI_PORT: $QBITTORRENT_WEBUI_PORT
      TORRENTING_PORT: $QBITTORRENT_TORRENTING_PORT
      PUID: $PUID
      PGID: $PGID
    volumes:
      - ${QBITTORRENT_CONFIG_LOCATION}:/config
      - ${QBITTORRENT_DOWNLOADS_LOCATION}:/downloads
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:8080
      - ${QBITTORRENT_TORRENTING_PORT}:6881
      - ${QBITTORRENT_TORRENTING_PORT}:6881/udp
    networks:
      - media-server-network
    restart: unless-stopped

networks:
  media-server-network:
    name: media-server-network
