services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VAULTWARDEN_VERSION}
    environment:
      SIGNUPS_ALLOWED: $VAULTWARDEN_SIGNUPS_ALLOWED
      DOMAIN: $VAULTWARDEN_DOMAIN
    volumes:
      - ${VAULTWARDEN_DATA_LOCATION}:/data/
    networks:
      - media-server-network
    restart: unless-stopped

networks:
  media-server-network:
    name: media-server-network
