services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    volumes:
      - ${JELLYFIN_CONFIG_LOCATION}:/config
      - ${JELLYFIN_CACHE_LOCATION}:/cache
      - ${JELLYFIN_TVSHOWS_LOCATION}:/data/tvshows
      - ${JELLYFIN_MOVIES_LOCATION}:/data/movies
      - ${JELLYFIN_MUSIC_LOCATION}:/data/music
    environment:
      - TZ=${TZ}
    networks:
      - media-server-network
    restart: unless-stopped

networks:
  media-server-network:
    name: media-server-network
